apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: sample-nodejs-app
  namespace: default
spec:
  project: default

  source:
    repoURL: https://github.com/inkredusk/sample-nodejs-app.git
    targetRevision: ingress-test
    path: node-app
  destination: 
    server: https://kubernetes.default.svc
    namespace: node-app

  syncPolicy:
    syncOptions:
    - CreateNamespace=true

    automated:
      selfHeal: true
      prune: true