name: CI

on:
  push:
    branches:
      - 'main'
      - 'develop'
      - 'ingress-test'
  workflow_dispatch:
env:
  IMAGE_NAME: examplenodejsapp-dev
  
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Login to DockerHub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
        
    - name: Build and push
      uses: docker/build-push-action@v3
      with:
        context: .
        push: true
        tags: ${{ secrets.DOCKERHUB_USERNAME }}/${{ env.IMAGE_NAME }}:${{ github.run_number }}

    - name: Update Image Version
      id: imgupd
      uses: mikefarah/yq@master
      with:
          cmd: yq eval '.spec.template.spec.containers[0].image = "${{ secrets.DOCKERHUB_USERNAME }}/${{ env.IMAGE_NAME }}:${{ github.run_number }}"' -i node-app/deployment.yaml
        
    - uses: stefanzweifel/git-auto-commit-action@v4
      with:
          commit_message: Apply image name changes